### YamlMime:PowershellCmdlet
summary: |-
  Returns SecretStore configuration information.
module: Microsoft.PowerShell.SecretStore
notes: |-
  The `AllUsers` **Scope** is not supported. The **Scope** is always `CurrentUser`.
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.PowerShell.SecretStore.SecureStoreConfig" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- Get-SecretStoreConfiguration [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\> Get-SecretStoreConfiguration

          Scope Authentication PasswordTimeout Interaction
          ----- -------------- --------------- -----------
    CurrentUser       Password             900      Prompt
  description: |-
    This example shows the current configuration for **SecretStore**. It is configured for the current
    user. It requires a password for initial access in a session and prompts the user for it in an
    interactive session. After fifteen minutes, the password is required again for access.
  summary: ""
uid: Microsoft.PowerShell.SecretStore.Get-SecretStoreConfiguration
name: Get-SecretStoreConfiguration
description: |-
  This cmdlet reads the SecretStore configuration file and returns the defined settings.
metadata:
  external help file: Microsoft.PowerShell.SecretStore.dll-Help.xml
  Module Name: Microsoft.PowerShell.SecretStore
  ms.date: 05/31/2022
  online version: https://learn.microsoft.com/powershell/module/microsoft.powershell.secretstore/get-secretstoreconfiguration?view=ps-modules&wt.mc_id=ps-gethelp
  schema: 2.0.0
