### YamlMime:PowershellCmdlet
summary: |-
  Configures the **SecretStore**.
module: Microsoft.PowerShell.SecretStore
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.PowerShell.SecretStore.SecureStoreConfig" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Set-SecretStoreConfiguration [-Scope <SecureStoreScope>] [-Authentication <Authenticate>]

   [-PasswordTimeout <Int32>] [-Interaction <Interaction>] [-Password <SecureString>] [-PassThru] [-WhatIf]

   [-Confirm] [<CommonParameters>]
- >-
  Set-SecretStoreConfiguration [-Default] [-Password <SecureString>] [-PassThru] [-WhatIf] [-Confirm]

   [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\> Set-SecretStoreConfiguration -Default

    Confirm
    Are you sure you want to perform this action?
    Performing the operation "Changes local store configuration" on target "SecretStore module local store".
    [Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): Y

          Scope Authentication PasswordTimeout Interaction
          ----- -------------- --------------- -----------
    CurrentUser       Password             900      Prompt
  description: |-
    This example restores the **SecretStore** to its default configuration.
  summary: ""
parameters:
- type: <xref href="Authenticate" data-throw-if-not-resolved="False" />
  name: Authentication
  description: |+
    Specifies how to authenticate access to the **SecretStore**. The value must be `Password` or `None`.
    If specified as `None`, the cmdlet enables access to the **SecretStore** without a password. The
    default authentication is `Password`.

    > [!CAUTION]
    > Setting the **Authentication** to `None` is less secure than `Password`. Specifying `None` may be
    > useful for testing scenarios but should not be used with important secrets.

  defaultValue: Password
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Default
  description: |+
    Indicates that the **SecretStore** should be set to its default configuration.

  defaultValue: "False"
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Interaction" data-throw-if-not-resolved="False" />
  name: Interaction
  description: |+
    Specifies whether the **SecretStore** should prompt a user when they access it. If the value is
    `Prompt`, the user is prompted for their password in interactive sessions when required. If the
    value is `None`, the user is not prompted for a password. If the value is `None` and a password is
    required, the cmdlet requiring the password throws a
    **Microsoft.PowerShell.SecretStore.PasswordRequiredException** error.

  defaultValue: "False"
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PassThru
  description: |+
    Indicates that the cmdlet should return the **SecretStore** configuration after updating it. By
    default, the cmdlet returns no output.

  defaultValue: "False"
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SecureString" data-throw-if-not-resolved="False" />
  name: Password
  description: |+
    Specifies the password needed to access the **SecretStore**. This parameter cannot be used to change
    the existing password. To change the existing password, use `Set-SecretStorePassword`.

    When this parameter is used with the **Authenticate** parameter to change the configuration for
    authentication from `None` to `Password`, this parameter's value is set as the new password for the
    **SecretStore**.

    When this parameter is used with the **Authenticate** parameter to change the configuration for
    authentication from `Password` to `None`, this parameter's value must be the current password for the
    **SecretStore**. It is used to authorize the configuration change.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: PasswordTimeout
  description: |+
    Specifies how many seconds the **SecretStore** remains unlocked after authenticating with a
    password. After the timeout has elapsed, the current password value is invalidated for the session.
    Accessing the **SecretStore** after the timeout requires the password again.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SecureStoreScope" data-throw-if-not-resolved="False" />
  name: Scope
  description: |+
    Specifies the context the **SecretStore** is configured for. Only `CurrentUser` is currently
    supported.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: CurrentUser, AllUsers
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs. The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Microsoft.PowerShell.SecretStore.Set-SecretStoreConfiguration
name: Set-SecretStoreConfiguration
description: |-
  This cmdlet configures the **SecretStore** for the current user.
metadata:
  external help file: Microsoft.PowerShell.SecretStore.dll-Help.xml
  Module Name: Microsoft.PowerShell.SecretStore
  ms.date: 05/31/2022
  online version: https://learn.microsoft.com/powershell/module/microsoft.powershell.secretstore/set-secretstoreconfiguration?view=ps-modules&wt.mc_id=ps-gethelp
  schema: 2.0.0
