### YamlMime:PowershellCmdlet
summary: |-
  Import a PowerShell Crescendo json file.
module: Microsoft.PowerShell.Crescendo
notes: |-
  The object returned by `Import-CommandConfiguration` is converted through the `ToString` method.
  Generally, you should use the `Export-CrescendoModule` to create a PowerShell `.psm1` file.
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="A Command object" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Export-CrescendoModule
  href: Export-CrescendoModule.yml
syntaxes:
- Import-CommandConfiguration [-file] <String> [<CommonParameters>]
examples:
- title: EXAMPLE 1
  code: |-
    Import-CommandConfiguration ifconfig.crescendo.json

    Verb                    : Invoke
    Noun                    : ifconfig
    OriginalName            : ifconfig
    OriginalCommandElements :
    Aliases                 :
    DefaultParameterSetName :
    SupportsShouldProcess   : False
    SupportsTransactions    : False
    NoInvocation            : False
    Description             : This is a description of the generated function
    Usage                   : .SYNOPSIS
                              Run invoke-ifconfig
    Parameters              : {[Parameter()]
                              [string]$Interface = ""}
    Examples                :
    OriginalText            :
    HelpLinks               :
    OutputHandlers          :
  description: ""
  summary: ""
parameters:
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: file
  isRequired: true
  description: |+
    The JSON file that represents the command to be wrapped.

  defaultValue: None
  position: "0"
  aliases: ""
  parameterValueGroup: ""
uid: Microsoft.PowerShell.Crescendo.Import-CommandConfiguration
name: Import-CommandConfiguration
description: |-
  This cmdlet exports an object that can be converted into a function that acts as a proxy for the
  platform specific command. The resultant object may then be used to call a native command that can
  participate in the PowerShell pipeline. The `ToString` method of the output object returns a string
  that can be used to create a function that calls the native command. Microsoft Windows, Linux, and
  macOS can run the generated function, if the native command is on all platforms.
metadata:
  external help file: Microsoft.PowerShell.Crescendo-help.xml
  Module Name: Microsoft.PowerShell.Crescendo
  ms.date: 12/13/2022
  online version: https://learn.microsoft.com/powershell/module/microsoft.powershell.crescendo/import-commandconfiguration?view=ps-modules&wt.mc_id=ps-gethelp
  schema: 2.0.0
